### ISSUE TITLE
benign_train.npy

### ISSUE THREAD

**Issue by ghost** [Shakib-IO/KD-lesions#1]
Hello there!

I'm trying to run the code but in the following line I have an error. 
benign_train = np.load('/content/drive/MyDrive/CSE465/Dataset/benign_train.npy')

The error is: 
OSError: [Errno 107] Transport endpoint is not connected: 'drive/MyDrive/CSE465/Dataset/benign_train.npy'

Do I need to download something else? Am I doing something wrong?
I would appreciate your help :)

**Comment by Shakib-IO** [comment]
You need to modify the path according to your environment. 
I'll upload the .npy files in few weeks.

**Comment by Shakib-IO** [comment]
Find the .npy files [here](https://github.com/Shakib-IO/KD-lesions/releases/tag/V1.0)
